spring:
  config:
    activate:
      on-profile: default
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:~/pickerdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      connection-timeout: 10000
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
environment: default env
web-driver:
  name: Remote Chrome Driver
  type: chrome
  browser-version: 98.0
  grid-url: http://localhost:4444

---

spring:
  config:
    activate:
      on-profile: prod
environment: PROD env
web-driver:
  name: Remote Chrome Driver
  type: chrome
  browser-version: 98.0
  grid-url: http://localhost:4444