-- 01. SET UP ROLE
INSERT INTO ROLE VALUES (1, 'ADMIN');
INSERT INTO ROLE VALUES (2, 'USER');

-- 02. SET UP USR (TESTING ONLY)
INSERT INTO USR VALUES (1, 'leobi', '$2a$10$Ps0nh03bNlGKvmE9KIghy.Oz7YwnQex6shWBcNIFZBYT1QzZcDenW');

-- 03. SET UP USR_ROLE (TESTING ONLY)
INSERT INTO USR_ROLE VALUES (1, 2);


